
[project]
name = "mcp_doffin"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "mcp>=1.2.0",
  "httpx>=0.27.0",
  "selectolax>=0.3.21",
  "tenacity>=9.0.0",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
